// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyDairyApp.Data;

#nullable disable

namespace MyDairyApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyDairyApp.Models.DairyEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DairyEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Content for entry 1",
                            Created = new DateTime(2025, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Entry 1"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Content for entry 2",
                            Created = new DateTime(2025, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Entry 2"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Content for entry 3",
                            Created = new DateTime(2025, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Entry 3"
                        },
                        new
                        {
                            Id = 4,
                            Content = "Content for entry 4",
                            Created = new DateTime(2025, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Entry 4"
                        },
                        new
                        {
                            Id = 5,
                            Content = "Content for entry 5",
                            Created = new DateTime(2025, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Entry 5"
                        },
                        new
                        {
                            Id = 6,
                            Content = "Content for entry 6",
                            Created = new DateTime(2025, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Entry 6"
                        },
                        new
                        {
                            Id = 7,
                            Content = "Content for entry 7",
                            Created = new DateTime(2025, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Entry 7"
                        },
                        new
                        {
                            Id = 8,
                            Content = "Content for entry 8",
                            Created = new DateTime(2025, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Entry 8"
                        },
                        new
                        {
                            Id = 9,
                            Content = "Content for entry 9",
                            Created = new DateTime(2025, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Entry 9"
                        },
                        new
                        {
                            Id = 10,
                            Content = "Content for entry 10",
                            Created = new DateTime(2025, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Entry 10"
                        },
                        new
                        {
                            Id = 11,
                            Content = "Content for entry 11",
                            Created = new DateTime(2025, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Entry 11"
                        },
                        new
                        {
                            Id = 12,
                            Content = "Content for entry 12",
                            Created = new DateTime(2025, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Entry 12"
                        },
                        new
                        {
                            Id = 13,
                            Content = "Content for entry 13",
                            Created = new DateTime(2025, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Entry 13"
                        },
                        new
                        {
                            Id = 14,
                            Content = "Content for entry 14",
                            Created = new DateTime(2025, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Entry 14"
                        },
                        new
                        {
                            Id = 15,
                            Content = "Content for entry 15",
                            Created = new DateTime(2025, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Entry 15"
                        },
                        new
                        {
                            Id = 16,
                            Content = "Content for entry 16",
                            Created = new DateTime(2025, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Entry 16"
                        },
                        new
                        {
                            Id = 17,
                            Content = "Content for entry 17",
                            Created = new DateTime(2025, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Entry 17"
                        },
                        new
                        {
                            Id = 18,
                            Content = "Content for entry 18",
                            Created = new DateTime(2025, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Entry 18"
                        },
                        new
                        {
                            Id = 19,
                            Content = "Content for entry 19",
                            Created = new DateTime(2025, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Entry 19"
                        },
                        new
                        {
                            Id = 20,
                            Content = "Content for entry 20",
                            Created = new DateTime(2025, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Entry 20"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
